### ISSUE TITLE
Module build failed: Error: Couldn't find preset "latest" relative to directory

### ISSUE THREAD

**Issue by sredbull** [lucefer/ellipsis-plus#2]
Module build failed: Error: Couldn't find preset "latest" relative to directory "node_modules/ellipsis-plus"
    at /node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (//node_modules/babel-loader/lib/index.js:175:20)

 @ ./node_modules/ellipsis-plus/src/ellipsis-plus.vue 8:0-123
 @ ./node_modules/ellipsis-plus/index.js
 @ ./src/main.js
 @ multi ./build/hot-reload.js ./src/main.js

**Comment by litoxy** [comment]
安装 babel-preset-latest
`npm install --save-dev babel-preset-latest`
